default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  socket: /var/lib/mysql/mysql.sock

development:
  <<: *default
  database: kentaro_development

test:
  <<: *default
  database: kentaro_test

production:
  <<: *default
  database: kentaro_production
  username: kentaro
  password: <%= ENV['KENTARO_DATABASE_PASSWORD'] %>
